/****************************************************************************
 * fs/procfs/fs_procfsmeminfo.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include <sys/types.h>
#include <sys/stat.h>

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include <errno.h>
#include <debug.h>
#include <ctype.h>

#include <nuttx/kmalloc.h>
#include <nuttx/pgalloc.h>
#include <nuttx/progmem.h>
#include <nuttx/sched.h>
#include <nuttx/mm/mm.h>
#include <nuttx/fs/fs.h>
#include <nuttx/fs/procfs.h>
#include <nuttx/mutex.h>
#include <nuttx/tls.h>

#include "fs_heap.h"
#include "sched/sched.h"

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MEMINFO

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define MEMINFO_LINELEN 512

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct meminfo_file_s
{
  struct procfs_file_s base;      /* Base open file structure */
  unsigned int linesize;          /* Number of valid characters in line[] */
  char line[MEMINFO_LINELEN];     /* Pre-allocated buffer for formatted lines */
};

#if defined(CONFIG_ARCH_HAVE_PROGMEM) && defined(CONFIG_FS_PROCFS_INCLUDE_PROGMEM)
struct progmem_info_s
{
  int arena;                      /* Total size of available progmem. */
  int ordblks;                    /* This is the number of free chunks */
  int aordblks;                   /* This is the number of allocated chunks */
  int mxordblk;                   /* Size of the largest free chunk */
  int uordblks;                   /* Total size of memory for allocated chunks */
  int fordblks;                   /* Total size of memory for free chunks. */
};
#endif

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

#if defined(CONFIG_ARCH_HAVE_PROGMEM) && defined(CONFIG_FS_PROCFS_INCLUDE_PROGMEM)
static void    meminfo_progmem(FAR struct progmem_info_s *progmem);
#endif

/* File system methods */

static int     meminfo_open(FAR struct file *filep, FAR const char *relpath,
                            int oflags, mode_t mode);
static int     meminfo_close(FAR struct file *filep);
#ifndef CONFIG_FS_PROCFS_EXCLUDE_MEMDUMP
static ssize_t memdump_read(FAR struct file *filep, FAR char *buffer,
                            size_t buflen);
static ssize_t memdump_write(FAR struct file *filep, FAR const char *buffer,
                             size_t buflen);
#endif
static ssize_t meminfo_read(FAR struct file *filep, FAR char *buffer,
                            size_t buflen);

/****************************************************************************
 * Public Data
 ****************************************************************************/

/* See fs_mount.c -- this structure is explicitly externed there.
 * We use the old-fashioned kind of initializers so that this will compile
 * with any compiler.
 */

const struct procfs_operations g_meminfo_operations =
{
  meminfo_open,   /* open */
  meminfo_close,  /* close */
  meminfo_read,   /* read */
};

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MEMDUMP
const struct procfs_operations g_memdump_operations =
{
  meminfo_open,   /* open */
  meminfo_close,  /* close */
  memdump_read,   /* read */
  memdump_write,  /* write */
};
#endif

static DEFINE_PER_CPU_BSS_BMP(FAR struct procfs_meminfo_entry_s *,
                              g_procfs_meminfo);
#define g_procfs_meminfo this_cpu_var_bmp(g_procfs_meminfo)
static
DEFINE_PER_CPU_BMP(mutex_t, g_procfs_meminfo_lock) = NXMUTEX_INITIALIZER;
#define g_procfs_meminfo_lock this_cpu_var_bmp(g_procfs_meminfo_lock)

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: meminfo_progmem
 *
 * Description:
 *   The moral equivalent of mallinfo() for prog mem
 *
 *   TODO Max block size only works on uniform prog mem
 *
 ****************************************************************************/

#if defined(CONFIG_ARCH_HAVE_PROGMEM) && defined(CONFIG_FS_PROCFS_INCLUDE_PROGMEM)
static void meminfo_progmem(FAR struct progmem_info_s *progmem)
{
  size_t page = 0;
  size_t stpage = 0xffff;
  size_t pagesize = 0;
  ssize_t status;

  progmem->arena    = 0;
  progmem->ordblks  = 0;
  progmem->aordblks = 0;
  progmem->fordblks = 0;
  progmem->uordblks = 0;
  progmem->mxordblk = 0;

  for (status = 0, page = 0; status >= 0; page++)
    {
      status   = up_progmem_ispageerased(page);
      pagesize = up_progmem_pagesize(page);

      progmem->arena += pagesize;

      /* Is this beginning of new free space section */

      if (status == 0)
        {
          if (stpage == 0xffff)
            {
              stpage = page;
            }

          progmem->fordblks += pagesize;
          progmem->ordblks++;
        }
      else if (status != 0)
        {
          progmem->aordblks++;
          progmem->uordblks += pagesize;

          if (stpage != 0xffff && up_progmem_isuniform())
            {
              stpage = page - stpage;
              if (stpage > progmem->mxordblk)
                {
                  progmem->mxordblk = stpage;
                }

              stpage = 0xffff;
            }
        }
    }

  progmem->mxordblk *= pagesize;
}
#endif

/****************************************************************************
 * Name: meminfo_open
 ****************************************************************************/

static int meminfo_open(FAR struct file *filep, FAR const char *relpath,
                        int oflags, mode_t mode)
{
  FAR struct meminfo_file_s *procfile;

  finfo("Open '%s'\n", relpath);

  /* Allocate a container to hold the file attributes */

  procfile = fs_heap_zalloc(sizeof(struct meminfo_file_s));
  if (!procfile)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* Save the attributes as the open-specific state in filep->f_priv */

  filep->f_priv = procfile;
  return OK;
}

/****************************************************************************
 * Name: meminfo_close
 ****************************************************************************/

static int meminfo_close(FAR struct file *filep)
{
  FAR struct meminfo_file_s *procfile;

  /* Recover our private data from the struct file instance */

  procfile = (FAR struct meminfo_file_s *)filep->f_priv;
  DEBUGASSERT(procfile);

  /* Release the file attributes structure */

  fs_heap_free(procfile);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: meminfo_read
 ****************************************************************************/

static ssize_t meminfo_read(FAR struct file *filep, FAR char *buffer,
                            size_t buflen)
{
  FAR struct meminfo_file_s *procfile;
  size_t linesize;
  size_t copysize;
  size_t totalsize;
  off_t offset;

  finfo("buffer=%p buflen=%d\n", buffer, (int)buflen);

  DEBUGASSERT(buffer != NULL && buflen > 0);
  offset = filep->f_pos;

  /* Recover our private data from the struct file instance */

  procfile = (FAR struct meminfo_file_s *)filep->f_priv;
  DEBUGASSERT(procfile);

  /* The first line is the headers */

  linesize  = procfs_snprintf(procfile->line, MEMINFO_LINELEN,
                              "%11s%11s%11s%11s%11s%7s%7s%s\n",
                              "total", "used", "free", "maxused",
                              "maxfree", "nused", "nfree", " name");

  copysize  = procfs_memcpy(procfile->line, linesize, buffer, buflen,
                            &offset);
  totalsize = copysize;

  /* Followed by information about the memory resources */

  FAR const struct procfs_meminfo_entry_s *entry;

  DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
  for (entry = g_procfs_meminfo; entry != NULL; entry = entry->next)
    {
      if (buflen > 0)
        {
          struct mallinfo info;

          buffer    += copysize;
          buflen    -= copysize;

          /* Show heap information */

          if (entry->mallinfo)
            {
              info = entry->mallinfo(entry->heap);
            }
          else
            {
              info = mm_mallinfo(entry->heap);
            }

          linesize   = procfs_snprintf(procfile->line, MEMINFO_LINELEN,
                                       "%11lu%11lu%11lu%11lu%11lu"
                                       "%7lu%7lu %s\n",
                                       (unsigned long)info.arena,
                                       (unsigned long)info.uordblks,
                                       (unsigned long)info.fordblks,
                                       (unsigned long)info.usmblks,
                                       (unsigned long)info.mxordblk,
                                       (unsigned long)info.aordblks,
                                       (unsigned long)info.ordblks,
                                       entry->name);
          copysize   = procfs_memcpy(procfile->line, linesize, buffer,
                                     buflen, &offset);
          totalsize += copysize;
        }
    }

  DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));
#ifdef CONFIG_MM_PGALLOC
  if (buflen > 0)
    {
      struct pginfo_s pg_info;
      unsigned long total;
      unsigned long available;
      unsigned long allocated;
      unsigned long max;

      buffer    += copysize;
      buflen    -= copysize;

      /* Show page allocator information */

      mm_pginfo(&pg_info);

      total      = (unsigned long)pg_info.ntotal << MM_PGSHIFT;
      available  = (unsigned long)pg_info.nfree  << MM_PGSHIFT;
      allocated  = total - available;
      max        = (unsigned long)pg_info.mxfree << MM_PGSHIFT;

      linesize   = procfs_snprintf(procfile->line, MEMINFO_LINELEN,
                                   "%11lu%11lu%11lu%11lu %s\n",
                                   total, allocated, available, max, "Page");

      copysize   = procfs_memcpy(procfile->line, linesize, buffer, buflen,
                                 &offset);
      totalsize += copysize;
    }
#endif

#if defined(CONFIG_ARCH_HAVE_PROGMEM) && defined(CONFIG_FS_PROCFS_INCLUDE_PROGMEM)
  if (buflen > 0)
    {
      struct progmem_info_s progmem;

      buffer    += copysize;
      buflen    -= copysize;

      /* The second line is the memory data */

      meminfo_progmem(&progmem);

      linesize   = procfs_snprintf(procfile->line, MEMINFO_LINELEN,
                                   "%11lu%11lu%11lu%11lu%7lu%7lu %s\n",
                                   (unsigned long)progmem.arena,
                                   (unsigned long)progmem.uordblks,
                                   (unsigned long)progmem.fordblks,
                                   (unsigned long)progmem.mxordblk,
                                   (unsigned long)progmem.aordblks,
                                   (unsigned long)progmem.ordblks
                                   "Prog");
      copysize   = procfs_memcpy(procfile->line, linesize, buffer, buflen,
                                 &offset);
      totalsize += copysize;
    }
#endif

  /* Update the file offset */

  filep->f_pos += totalsize;
  return totalsize;
}

/****************************************************************************
 * Name: memdump_read
 ****************************************************************************/

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MEMDUMP
static ssize_t memdump_read(FAR struct file *filep, FAR char *buffer,
                            size_t buflen)
{
  FAR struct meminfo_file_s *procfile;
  size_t linesize;
  size_t copysize;
  off_t offset;

  finfo("buffer=%p buflen=%d\n", buffer, (int)buflen);

  DEBUGASSERT(buffer != NULL && buflen > 0);
  offset = filep->f_pos;

  /* Recover our private data from the struct file instance */

  procfile = (FAR struct meminfo_file_s *)filep->f_priv;
  DEBUGASSERT(procfile);

  linesize  = procfs_snprintf(procfile->line, MEMINFO_LINELEN,
                 "usage: <used/free/orphan"
#if CONFIG_MM_HEAP_MEMPOOL_THRESHOLD > 0
                 "/mempool"
#endif
#if CONFIG_MM_HEAP_BIGGEST_COUNT > 0
                  "/biggest"
#endif
#ifdef CONFIG_MM_RECORD_STACK
                  "/on/off"
#endif
#ifdef CONFIG_MM_RECORD_PID
                 "/leak/pid"
#endif
#ifdef CONFIG_MM_RECORD_SEQNO
                 "> <seqmin> <seqmax"
#endif
                 ">\n"
                 "used: dump all allocated node\n"
                 "free: dump all free node\n"
                 "orphan: dump allocated free neighbored node\n"
#if CONFIG_MM_HEAP_MEMPOOL_THRESHOLD > 0
                 "mempool: dump all mempool alloc node\n"
#endif
#if CONFIG_MM_HEAP_BIGGEST_COUNT > 0
                  "biggest: dump allocated top n node\n"
#endif
#ifdef CONFIG_MM_RECORD_STACK
                 "on/off: set backtrace enabled state\n"
#endif
#ifdef CONFIG_MM_RECORD_PID
                 "leak: dump all leaked node\n"
                 "pid: dump pid allocated node\n"
#endif
#ifdef CONFIG_MM_RECORD_SEQNO
                 "The current sequence number %lu\n",
                 g_mm_seqno
#endif
                 );

  copysize  = procfs_memcpy(procfile->line, linesize, buffer, buflen,
                            &offset);
  filep->f_pos += copysize;
  return copysize;
}
#endif

/****************************************************************************
 * Name: memdump_write
 ****************************************************************************/

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MEMDUMP
static ssize_t memdump_write(FAR struct file *filep, FAR const char *buffer,
                             size_t buflen)
{
  FAR struct procfs_meminfo_entry_s *entry;
  FAR struct meminfo_file_s *procfile;
  struct mm_memdump_s dump =
    {
      PID_MM_ALLOC,
#ifdef CONFIG_MM_RECORD_SEQNO
      0,
      ULONG_MAX
#endif
    };

#ifdef CONFIG_MM_RECORD
  FAR char *p;
#endif
#ifdef CONFIG_MM_RECORD_STACK
  FAR struct tcb_s *tcb;
#endif

  DEBUGASSERT(buffer != NULL && buflen > 0);

  /* Recover our private data from the struct file instance */

  procfile = filep->f_priv;
  DEBUGASSERT(procfile);

#ifdef CONFIG_MM_RECORD_STACK
  if (strcmp(buffer, "on") == 0)
    {
      DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
      for (entry = g_procfs_meminfo; entry != NULL; entry = entry->next)
        {
          entry->backtrace = true;
        }

      DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));
      return buflen;
    }
  else if (strcmp(buffer, "off") == 0)
    {
      DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
      for (entry = g_procfs_meminfo; entry != NULL; entry = entry->next)
        {
          entry->backtrace = false;
        }

      DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));
      return buflen;
    }
  else if ((p = strstr(buffer, "on")) != NULL)
    {
      FAR struct tls_info_s *info;

      *p = '\0';
      dump.pid = atoi(buffer);
      tcb = nxsched_get_tcb(dump.pid);
      if (tcb == NULL)
        {
          return -EINVAL;
        }

      info = nxsched_get_tls(tcb);
      if (info != NULL)
        {
          info->tl_flags |= TLS_FLAG_HEAP_DUMP;
        }

      nxsched_put_tcb(tcb);
      return buflen;
    }
  else if ((p = strstr(buffer, "off")) != NULL)
    {
      FAR struct tls_info_s *info;

      *p = '\0';
      dump.pid = atoi(buffer);
      tcb = nxsched_get_tcb(dump.pid);
      if (tcb == NULL)
        {
          return -EINVAL;
        }

      info = nxsched_get_tls(tcb);
      if (info != NULL)
        {
          info->tl_flags &= ~TLS_FLAG_HEAP_DUMP;
        }

      nxsched_put_tcb(tcb);
      return buflen;
    }
#endif

  switch (buffer[0])
    {
      case 'u':
        dump.pid = PID_MM_ALLOC;

#ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 4;
        goto dump;
#endif
        break;

      case 'f':
        dump.pid = PID_MM_FREE;

#ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 4;
        goto dump;
#endif
        break;

#ifdef CONFIG_MM_RECORD_PID
      case 'l':
        dump.pid = PID_MM_LEAK;

#  ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 4;
        goto dump;
#  endif
        break;
#endif

#if CONFIG_MM_HEAP_MEMPOOL_THRESHOLD > 0
      case 'm':
        dump.pid = PID_MM_MEMPOOL;

#  ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 7;
        goto dump;
#  endif
        break;
#endif

#if CONFIG_MM_HEAP_BIGGEST_COUNT > 0
      case 'b':
        dump.pid = PID_MM_BIGGEST;
#  ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 7;
        goto dump;
#  endif
        break;
#endif

      case 'o':
        dump.pid = PID_MM_ORPHAN;
#ifdef CONFIG_MM_RECORD_SEQNO
        p = (FAR char *)buffer + 6;
        goto dump;
#endif
        break;

      default:
#ifdef CONFIG_MM_RECORD_PID
        if (!isdigit(buffer[0]))
          {
            return buflen;
          }

        dump.pid = strtol(buffer, &p, 0);
        if (!isdigit(*(p + 1)))
          {
            break;
          }
#else
        return buflen;
#endif

#ifdef CONFIG_MM_RECORD_SEQNO
dump:
        dump.seqmin = strtoul(p + 1, &p, 0);
        if (!isdigit(*(p + 1)))
          {
            break;
          }

        dump.seqmax = strtoul(p + 1, &p, 0);
#endif
    }

  DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
  for (entry = g_procfs_meminfo; entry != NULL; entry = entry->next)
    {
      if (entry->memdump)
        {
          entry->memdump(entry->heap, &dump);
        }
      else
        {
          mm_memdump(entry->heap, &dump);
        }
    }

  DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));
  return buflen;
}
#endif

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: procfs_register_meminfo
 *
 * Description:
 *   Add a new meminfo entry to the procfs file system.
 *   Allocates an entry dynamically and initializes it.
 *
 * Input Parameters:
 *   name      - The name of the memory region
 *   heap      - The heap to register
 *   mallinfo_handler  - Optional custom mallinfo handler
 *   memdump_handler   - Optional custom memdump handler
 *
 * Returned Value:
 *   Pointer to the allocated entry on success, NULL on failure.
 *   This pointer must be passed to procfs_unregister_meminfo.
 *
 ****************************************************************************/

FAR struct procfs_meminfo_entry_s *
procfs_register_meminfo(FAR const char *name, FAR struct mm_heap_s *heap,
                        mm_mallinfo_handler_t mallinfo_handler,
                        mm_memdump_handler_t memdump_handler)
{
  FAR struct procfs_meminfo_entry_s *entry;

  /* Allocate entry from kernel heap */

  entry = kmm_zalloc(sizeof(struct procfs_meminfo_entry_s));
  if (entry == NULL)
    {
      return NULL;
    }

  /* Initialize the entry */

  entry->name      = name;
  entry->heap      = heap;
  entry->mallinfo  = mallinfo_handler;
  entry->memdump   = memdump_handler;
#ifdef CONFIG_MM_RECORD_STACK
#  ifdef CONFIG_MM_RECORD_STACK_DEFAULT
  entry->backtrace = true;
#  else
  entry->backtrace = false;
#  endif
#endif

  /* Add to linked list */

  DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
  entry->next = g_procfs_meminfo;
  g_procfs_meminfo = entry;
  DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));

  return entry;
}

/****************************************************************************
 * Name: procfs_unregister_meminfo
 *
 * Description:
 *   Remove a meminfo entry from the procfs file system.
 *   Frees the entry that was allocated by procfs_register_meminfo.
 *
 * Input Parameters:
 *   entry - The entry returned by procfs_register_meminfo.
 *
 ****************************************************************************/

void procfs_unregister_meminfo(FAR struct procfs_meminfo_entry_s *entry)
{
  FAR struct procfs_meminfo_entry_s **cur;

  DEBUGVERIFY(nxmutex_lock(&g_procfs_meminfo_lock));
  for (cur = &g_procfs_meminfo; *cur != NULL; cur = &(*cur)->next)
    {
      if (*cur == entry)
        {
          *cur = entry->next;
          break;
        }
    }

  DEBUGVERIFY(nxmutex_unlock(&g_procfs_meminfo_lock));

  kmm_delayfree(entry);
}
#endif /* !CONFIG_FS_PROCFS_EXCLUDE_MEMINFO */
