/****************************************************************************
 * fs/procfs/fs_procfscritmon.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include <sys/types.h>
#include <sys/stat.h>

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include <errno.h>
#include <debug.h>

#include <nuttx/clock.h>
#include <nuttx/kmalloc.h>
#include <nuttx/fs/fs.h>
#include <nuttx/fs/procfs.h>
#include <nuttx/sched.h>

#include "fs_heap.h"

#if !defined(CONFIG_DISABLE_MOUNTPOINT) && defined(CONFIG_FS_PROCFS) && \
     defined(CONFIG_SCHED_CRITMONITOR)

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define CRITMON_LINELEN 64

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct critmon_file_s
{
  struct procfs_file_s  base;   /* Base open file structure */
  unsigned int linesize;        /* Number of valid characters in line[] */
  char line[CRITMON_LINELEN];   /* Pre-allocated buffer for formatted lines */
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* File system methods */

static int     critmon_open(FAR struct file *filep, FAR const char *relpath,
                 int oflags, mode_t mode);
static int     critmon_close(FAR struct file *filep);
static ssize_t critmon_read(FAR struct file *filep, FAR char *buffer,
                 size_t buflen);

/****************************************************************************
 * Public Data
 ****************************************************************************/

/* See fs_mount.c -- this structure is explicitly externed there.
 * We use the old-fashioned kind of initializers so that this will compile
 * with any compiler.
 */

const struct procfs_operations g_critmon_operations =
{
  critmon_open,       /* open */
  critmon_close,      /* close */
  critmon_read,       /* read */
};

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: critmon_open
 ****************************************************************************/

static int critmon_open(FAR struct file *filep, FAR const char *relpath,
                      int oflags, mode_t mode)
{
  FAR struct critmon_file_s *attr;

  finfo("Open '%s'\n", relpath);

  /* PROCFS is read-only.  Any attempt to open with any kind of write
   * access is not permitted.
   *
   * REVISIT:  Write-able proc files could be quite useful.
   */

  if ((oflags & O_WRONLY) != 0 || (oflags & O_RDONLY) == 0)
    {
      ferr("ERROR: Only O_RDONLY supported\n");
      return -EACCES;
    }

  /* Allocate a container to hold the file attributes */

  attr = fs_heap_zalloc(sizeof(struct critmon_file_s));
  if (!attr)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* Save the attributes as the open-specific state in filep->f_priv */

  filep->f_priv = (FAR void *)attr;
  return OK;
}

/****************************************************************************
 * Name: critmon_close
 ****************************************************************************/

static int critmon_close(FAR struct file *filep)
{
  FAR struct critmon_file_s *attr;

  /* Recover our private data from the struct file instance */

  attr = (FAR struct critmon_file_s *)filep->f_priv;
  DEBUGASSERT(attr);

  /* Release the file attributes structure */

  fs_heap_free(attr);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: critmon_read_cpu
 ****************************************************************************/

static ssize_t critmon_read_cpu(FAR struct critmon_file_s *attr,
                                FAR char *buffer, size_t buflen,
                                FAR off_t *offset, int cpu)
{
  struct timespec maxtime;
  size_t linesize;
  size_t copysize;
  size_t totalsize;
#if CONFIG_SCHED_CRITMONITOR_MAXTIME_BUSYWAIT >= 0
  struct timespec alltime;
  clock_t elapsed;
  uint32_t rate;
#endif
#if CONFIG_SCHED_CRITMONITOR_MAXTIME_PREEMPTION >= 0
#  ifdef CONFIG_SMP
  clock_t *premp_max = &per_cpu_var(g_premp_max, cpu);
#  else
  clock_t *premp_max = &this_cpu_var(g_premp_max);
#  endif
#endif
#if CONFIG_SCHED_CRITMONITOR_MAXTIME_CSECTION >= 0
#  ifdef CONFIG_SMP
  clock_t *crit_max = &per_cpu_var(g_crit_max, cpu);
#  else
  clock_t *crit_max = &this_cpu_var(g_crit_max);
#  endif
#endif
#if CONFIG_SCHED_CRITMONITOR_MAXTIME_BUSYWAIT >= 0
#  ifdef CONFIG_SMP
  clock_t *busywait_max = &per_cpu_var(g_busywait_max, cpu);
#  else
  clock_t *busywait_max = &this_cpu_var(g_busywait_max);
#  endif
#endif
  UNUSED(maxtime);
  UNUSED(linesize);
  UNUSED(copysize);

  totalsize = 0;

  /* Generate output for CPU Serial Number */

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, "%d", cpu);
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;
  buffer    += copysize;
  buflen    -= copysize;

  if (buflen <= 0)
    {
      return totalsize;
    }

#if CONFIG_SCHED_CRITMONITOR_MAXTIME_PREEMPTION >= 0
  /* Convert the for maximum time pre-emption disabled */

  if (*premp_max > 0)
    {
      perf_convert(*premp_max, &maxtime);
    }
  else
    {
      maxtime.tv_sec = 0;
      maxtime.tv_nsec = 0;
    }

  /* Reset the maximum */

  *premp_max = 0;

  /* Generate output for maximum time pre-emption disabled */

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, ",%lu.%09lu",
                             (unsigned long)maxtime.tv_sec,
                             (unsigned long)maxtime.tv_nsec);
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;
  buffer    += copysize;
  buflen    -= copysize;

  if (buflen <= 0)
    {
      return totalsize;
    }
#endif

#if CONFIG_SCHED_CRITMONITOR_MAXTIME_CSECTION >= 0
  /* Convert and generate output for maximum time in a critical section */

  if (*crit_max > 0)
    {
      perf_convert(*crit_max, &maxtime);
    }
  else
    {
      maxtime.tv_sec = 0;
      maxtime.tv_nsec = 0;
    }

  /* Reset the maximum */

  *crit_max = 0;

  /* Generate output for maximum time in a critical section */

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, ",%lu.%09lu",
                             (unsigned long)maxtime.tv_sec,
                             (unsigned long)maxtime.tv_nsec);
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;
  buffer    += copysize;
  buflen    -= copysize;

  if (buflen <= 0)
    {
      return totalsize;
    }
#endif

#if CONFIG_SCHED_CRITMONITOR_MAXTIME_BUSYWAIT >= 0
  /* Convert and generate output for max busywait time when trying spinlock */

  if (*busywait_max > 0)
    {
      perf_convert(*busywait_max, &maxtime);
    }
  else
    {
      maxtime.tv_sec = 0;
      maxtime.tv_nsec = 0;
    }

  /* Reset the maximum */

  *busywait_max = 0;

  /* Generate output for max busywait time to enter csection(get spinlock) */

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, ",%lu.%09lu",
                             (unsigned long)maxtime.tv_sec,
                             (unsigned long)maxtime.tv_nsec);
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;
  buffer    += copysize;
  buflen    -= copysize;

  if (buflen <= 0)
    {
      return totalsize;
    }

  /* Convert and generate output for all busywait time when trying spinlock */

  if (*busywait_max > 0)
    {
      perf_convert(*busywait_max, &alltime);
    }
  else
    {
      alltime.tv_sec = 0;
      alltime.tv_nsec = 0;
    }

  elapsed = clock() * CONFIG_USEC_PER_TICK;
  rate = (uint64_t)(alltime.tv_sec * 1000000 + alltime.tv_nsec / 1000) *
         1000000 / elapsed;

  /* Generate output for all busywait time to enter csection(get spinlock) */

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, ",%lu.%09lu %2"
                             PRId32 ".%04" PRId32 "%%",
                             (unsigned long)alltime.tv_sec,
                             (unsigned long)alltime.tv_nsec,
                             rate / 10000, rate % 10000);
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;
  buffer    += copysize;
  buflen    -= copysize;

  if (buflen <= 0)
    {
      return totalsize;
    }
#endif

  linesize = procfs_snprintf(attr->line, CRITMON_LINELEN, "\n");
  copysize = procfs_memcpy(attr->line, linesize, buffer, buflen, offset);

  totalsize += copysize;

  return totalsize;
}

/****************************************************************************
 * Name: critmon_read
 ****************************************************************************/

static ssize_t critmon_read(FAR struct file *filep, FAR char *buffer,
                            size_t buflen)
{
  FAR struct critmon_file_s *attr;
  off_t offset;
  ssize_t ret;
  int cpu;

  finfo("buffer=%p buflen=%d\n", buffer, (int)buflen);

  /* Recover our private data from the struct file instance */

  attr = (FAR struct critmon_file_s *)filep->f_priv;
  DEBUGASSERT(attr);

  ret    = 0;
  offset = filep->f_pos;

  /* Get the status for each CPU  */

  for (cpu = 0; cpu < CONFIG_SMP_NCPUS; cpu++)
    {
      ssize_t nbytes = critmon_read_cpu(attr, buffer + ret, buflen - ret,
                                        &offset, cpu);

      ret += nbytes;
#ifdef CONFIG_SMP
      if (ret > buflen)
#endif
        {
          break;
        }
    }

  if (ret > 0)
    {
      filep->f_pos += ret;
    }

  return ret;
}

#endif /* !CONFIG_DISABLE_MOUNTPOINT && CONFIG_FS_PROCFS && CONFIG_SCHED_CRITMONITOR */
