/****************************************************************************
 * drivers/rpmsg/rpmsg_procfs.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include <sys/types.h>
#include <sys/stat.h>

#include <assert.h>
#include <errno.h>
#include <debug.h>
#include <fnmatch.h>

#include <nuttx/fs/fs.h>
#include <nuttx/fs/procfs.h>
#include <nuttx/kmalloc.h>
#include <nuttx/nuttx.h>
#include <nuttx/rpmsg/rpmsg.h>

#include "rpmsg.h"
#include "rpmsg_procfs.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define RPMSG_PROCFS_LINELEN 80

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct rpmsg_procfs_file_s
{
  struct procfs_file_s base;                         /* Base open file structure */
  char                 line[RPMSG_PROCFS_LINELEN];   /* Pre-allocated buffer for formatted lines */
};

struct rpmsg_procfs_info_s
{
  FAR struct rpmsg_procfs_file_s *procfile;
  size_t                          totalsize;
  FAR char                       *buffer;
  size_t                          buflen;
  off_t                           offset;
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* File system methods */

static int     rpmsg_procfs_open(FAR struct file *filep,
                                 FAR const char *relpath,
                                 int oflags, mode_t mode);
static int     rpmsg_procfs_close(FAR struct file *filep);
static ssize_t rpmsg_procfs_read(FAR struct file *filep, FAR char *buffer,
                                 size_t buflen);
static ssize_t rpmsg_procfs_write(FAR struct file *filep,
                                  FAR const char *buffer, size_t buflen);

/****************************************************************************
 * Private Data
 ****************************************************************************/

static const struct procfs_operations g_rpmsg_procfs_ops =
{
  rpmsg_procfs_open,   /* open */
  rpmsg_procfs_close,  /* close */
  rpmsg_procfs_read,   /* read */
  rpmsg_procfs_write,  /* write */
};

static const struct procfs_entry_s g_rpmsg_procfs_root =
{
  "rpmsg", &g_rpmsg_procfs_ops, PROCFS_FILE_TYPE
};

static DEFINE_PER_CPU_BSS_BMP(char,
                              g_rpmsg_procfs_filter[RPMSG_PROCFS_LINELEN]);
#define g_rpmsg_procfs_filter this_cpu_var_bmp(g_rpmsg_procfs_filter)

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rpmsg_procfs_open
 ****************************************************************************/

static int rpmsg_procfs_open(FAR struct file *filep, FAR const char *relpath,
                             int oflags, mode_t mode)
{
  FAR struct rpmsg_procfs_file_s *procfile;

  finfo("Open '%s'\n", relpath);

  /* Allocate a container to hold the file attributes */

  procfile = kmm_zalloc(sizeof(struct rpmsg_procfs_file_s));
  if (procfile == NULL)
    {
      rpmsgerr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* Save the attributes as the open-specific state in filep->f_priv */

  filep->f_priv = procfile;
  return OK;
}

/****************************************************************************
 * Name: rpmsg_procfs_close
 ****************************************************************************/

static int rpmsg_procfs_close(FAR struct file *filep)
{
  DEBUGASSERT(filep->f_priv);

  /* Release the file attributes structure */

  kmm_free(filep->f_priv);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: rpmsg_procfs_close
 ****************************************************************************/

static int rpmsg_procfs_handler(FAR struct rpmsg_s *rpmsg, FAR void *args)
{
  FAR struct rpmsg_procfs_info_s *procinfo =
    (FAR struct rpmsg_procfs_info_s *)args;
  size_t linesize;
  size_t copysize;

  if (procinfo->buflen > 0)
    {
      linesize = procfs_snprintf(procinfo->procfile->line,
                                 RPMSG_PROCFS_LINELEN,
                                 "%-15s%-15s\n",
                                 rpmsg->local_cpuname,
                                 rpmsg->cpuname);
      copysize = procfs_memcpy(procinfo->procfile->line, linesize,
                               procinfo->buffer, procinfo->buflen,
                               &procinfo->offset);
      procinfo->totalsize += copysize;
      procinfo->buffer += copysize;
      procinfo->buflen -= copysize;
    }

  return OK;
}

/****************************************************************************
 * Name: rpmsg_procfs_read
 ****************************************************************************/

static ssize_t rpmsg_procfs_read(FAR struct file *filep, FAR char *buffer,
                                 size_t buflen)
{
  FAR struct rpmsg_procfs_info_s procinfo;
  size_t copysize;
  size_t linesize;

  procinfo.offset = filep->f_pos;
  procinfo.procfile = filep->f_priv;
  linesize = procfs_snprintf(procinfo.procfile->line, RPMSG_PROCFS_LINELEN,
                             "Local CPU      Remote CPU\n");
  copysize = procfs_memcpy(procinfo.procfile->line, linesize,
                           buffer, buflen,
                           &procinfo.offset);

  buffer += copysize;
  buflen -= copysize;

  procinfo.totalsize = copysize;
  procinfo.buffer = buffer;
  procinfo.buflen = buflen;

  rpmsg_foreach(rpmsg_procfs_handler, &procinfo);

  filep->f_pos += procinfo.totalsize;
  return procinfo.totalsize;
}

/****************************************************************************
 * Name: rpmsg_procfs_write
 ****************************************************************************/

static ssize_t rpmsg_procfs_write(FAR struct file *filep,
                                  FAR const char *buffer, size_t buflen)
{
  if (buffer == NULL || buflen <= 1 || buflen >= RPMSG_PROCFS_LINELEN)
    {
      return -EINVAL;
    }

  memcpy(g_rpmsg_procfs_filter, buffer, buflen);
  g_rpmsg_procfs_filter[buflen] = '\0';

  return buflen;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rpmsg_procfs_trace_allow
 ****************************************************************************/

bool rpmsg_procfs_trace_allow(FAR const char *ept_name)
{
  return fnmatch(g_rpmsg_procfs_filter, ept_name, 0) == 0;
}

/****************************************************************************
 * Name: rpmsg_procfs_initialize
 ****************************************************************************/

void rpmsg_procfs_initialize(void)
{
  int ret;

  ret = procfs_register(&g_rpmsg_procfs_root);
  if (ret != OK)
    {
      rpmsgerr("ERROR: Failed to register rpmsg procfs %d\n", ret);
    }
}
