/****************************************************************************
 * drivers/rpmsg/rpmsg_procfs.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include <sys/types.h>
#include <sys/stat.h>

#include <assert.h>
#include <errno.h>
#include <debug.h>

#include <nuttx/fs/fs.h>
#include <nuttx/fs/procfs.h>
#include <nuttx/kmalloc.h>
#include <nuttx/nuttx.h>
#include <nuttx/rpmsg/rpmsg.h>

#include "rpmsg.h"
#include "rpmsg_procfs.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define RPMSG_PROCFS_LINELEN 80

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct rpmsginfo_file_s
{
  struct procfs_file_s base;                      /* Base open file structure */
  char                 line[RPMSGINFO_LINELEN];   /* Pre-allocated buffer for formatted lines */
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* File system methods */

static int     rpmsginfo_open(FAR struct file *filep,
                              FAR const char *relpath,
                              int oflags, mode_t mode);
static int     rpmsginfo_close(FAR struct file *filep);
static ssize_t rpmsginfo_read(FAR struct file *filep, FAR char *buffer,
                              size_t buflen);
static int     rpmsginfo_dup(FAR const struct file *oldp,
                             FAR struct file *newp);

/****************************************************************************
 * Private Data
 ****************************************************************************/

static const struct procfs_operations g_rpmsginfo_operations =
{
  rpmsginfo_open,   /* open */
  rpmsginfo_close,  /* close */
  rpmsginfo_read,   /* read */
  NULL,             /* write */
  NULL,             /* poll */
  rpmsginfo_dup,    /* dup */
};

static const struct procfs_entry_s g_rpmsg_procfs_root =
{
  "rpmsg", &g_rpmsginfo_operations, PROCFS_FILE_TYPE, 0444
};

static FAR struct rpmsg_procfs_entry_s *g_rpmsg_procfs_entry = NULL;

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rpmsginfo_open
 ****************************************************************************/

static int rpmsginfo_open(FAR struct file *filep, FAR const char *relpath,
                          int oflags, mode_t mode)
{
  FAR struct rpmsginfo_file_s *procfile;

  finfo("Open '%s'\n", relpath);

  /* Allocate a container to hold the file attributes */

  procfile = kmm_zalloc(sizeof(struct rpmsginfo_file_s));
  if (procfile == NULL)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* Save the attributes as the open-specific state in filep->f_priv */

  filep->f_priv = procfile;
  return OK;
}

/****************************************************************************
 * Name: rpmsginfo_close
 ****************************************************************************/

static int rpmsginfo_close(FAR struct file *filep)
{
  FAR struct rpmsginfo_file_s *procfile;

  /* Recover our private data from the struct file instance */

  procfile = filep->f_priv;
  DEBUGASSERT(procfile);

  /* Release the file attributes structure */

  kmm_free(procfile);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: rpmsginfo_read
 ****************************************************************************/

static ssize_t rpmsginfo_read(FAR struct file *filep, FAR char *buffer,
                              size_t buflen)
{
  FAR const struct rpmsg_procfs_entry_s *entry;
  FAR struct rpmsginfo_file_s *procfile;
  size_t totalsize = 0;
  size_t copysize = 0;
  size_t linesize;
  off_t offset;

  offset = filep->f_pos;
  procfile = filep->f_priv;

  linesize = procfs_snprintf(procfile->line, RPMSGINFO_LINELEN,
                             "%-15s%-15s\n",
                             "Local CPU", "Remote CPU");
  copysize = procfs_memcpy(procfile->line, linesize, buffer,
                           buflen, &offset);
  totalsize = copysize;

  for (entry = g_rpmsg_procfs_entry; entry != NULL; entry = entry->next)
    {
      if (buflen > 0)
        {
          FAR struct rpmsg_s *rpmsg = container_of(entry, struct rpmsg_s,
                                                   procfs);
          FAR struct rpmsg_device *rdev = rpmsg_get_rdev_by_rpmsg(rpmsg);

          buffer += copysize;
          buflen -= copysize;

          linesize = procfs_snprintf(procfile->line, RPMSGINFO_LINELEN,
                                     "%-15s%-15s\n",
                                     rpmsg_get_local_cpuname(rdev),
                                     rpmsg_get_cpuname(rdev));
          copysize = procfs_memcpy(procfile->line, linesize, buffer,
                                   buflen, &offset);
          totalsize += copysize;
        }
    }

  filep->f_pos += totalsize;
  return totalsize;
}

/****************************************************************************
 * Name: rpmsginfo_dup
 *
 * Description:
 *   Duplicate open file data in the new file structure.
 *
 ****************************************************************************/

static int rpmsginfo_dup(FAR const struct file *oldp, FAR struct file *newp)
{
  FAR struct rpmsginfo_file_s *oldattr;
  FAR struct rpmsginfo_file_s *newattr;

  finfo("Dup %p->%p\n", oldp, newp);

  /* Recover our private data from the old struct file instance */

  oldattr = oldp->f_priv;
  DEBUGASSERT(oldattr);

  /* Allocate a new container to hold the task and attribute selection */

  newattr = kmm_malloc(sizeof(struct rpmsginfo_file_s));
  if (newattr == NULL)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* The copy the file attributes from the old attributes to the new */

  memcpy(newattr, oldattr, sizeof(struct rpmsginfo_file_s));

  /* Save the new attributes in the new file structure */

  newp->f_priv = newattr;
  return OK;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: rpmsg_procfs_register
 *
 * Description:
 *   Add a new rpmsg entry to the procfs file system.
 *
 * Input Parameters:
 *   entry - Describes the entry to be registered.
 *
 ****************************************************************************/

void rpmsg_procfs_register(FAR struct rpmsg_procfs_entry_s *entry,
                           FAR const char *name)
{
  entry->name = name;
  entry->next = g_rpmsg_procfs_entry;
  g_rpmsg_procfs_entry = entry;
}

/****************************************************************************
 * Name: rpmsg_procfs_unregister
 *
 * Description:
 *   Remove a rpmsg entry from the procfs file system.
 *
 * Input Parameters:
 *   entry - Describes the entry to be unregistered.
 *
 ****************************************************************************/

void rpmsg_procfs_unregister(FAR struct rpmsg_procfs_entry_s *entry)
{
  FAR struct rpmsg_procfs_entry_s **cur;

  for (cur = &g_rpmsg_procfs_entry; *cur != NULL; cur = &(*cur)->next)
    {
      if (*cur == entry)
        {
          *cur = entry->next;
          break;
        }
    }
}

/****************************************************************************
 * Name: rpmsg_procfs_initialize
 ****************************************************************************/

void rpmsg_procfs_initialize(void)
{
  int ret;

  ret = procfs_register(&g_rpmsg_procfs_root);
  if (ret != OK)
    {
      ferr("ERROR: Failed to register rpmsg procfs\n");
    }
}
